#!/usr/bin/env python3
"""
Phase 4 -- generate the "thrust replay" firmware from a real .eng thrust curve.

Reads a RASP .eng file, resamples the thrust curve onto a uniform time grid,
scales it into DAC codes (0..255), and writes an ESP32 firmware that plays that
curve out the DAC while sampling it back on the ADC. This is a full dry-run of
the static-test data pipeline -- with no motor.

Usage:
    python gen_thrust_firmware.py /home/sebasvelace/openMotor/eng/E.eng
"""
import sys
import numpy as np

DT_MS = 2.0                 # playback/sample step (ms)
DAC_MIN, DAC_MAX = 30, 230  # keep inside the ADC's good linear range
OUT = "thrust_replay/main.cpp"


def parse_eng(path):
    t, f = [], []
    with open(path) as fh:
        header_seen = False
        for line in fh:
            line = line.strip()
            if not line or line.startswith(";"):
                continue
            if not header_seen:           # first non-comment line = header
                header_seen = True
                continue
            parts = line.split()
            if len(parts) == 2:
                t.append(float(parts[0]))
                f.append(float(parts[1]))
    return np.array(t), np.array(f)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "/home/sebasvelace/openMotor/eng/E.eng"
    t, f = parse_eng(path)

    burn = t[-1]
    i_true = np.trapezoid(f, t)                      # ground-truth impulse (N*s)
    f_max = f.max()

    dt = DT_MS / 1000.0
    t_grid = np.arange(0, burn + dt, dt)
    f_grid = np.interp(t_grid, t, f)
    n = len(t_grid)

    # Scale thrust -> DAC code
    dac = np.round(DAC_MIN + (DAC_MAX - DAC_MIN) * f_grid / f_max).astype(int)
    dac = np.clip(dac, 0, 255)

    print(f"Thrust curve : {path}")
    print(f"Burn time    : {burn*1000:.0f} ms  ->  {n} steps at {DT_MS:.0f} ms")
    print(f"Peak thrust  : {f_max:.1f} N")
    print(f"TRUE impulse : {i_true:.2f} N*s")

    arr = ", ".join(str(int(v)) for v in dac)
    firmware = f"""/*
 * DAQ Fase 4 -- Thrust-curve replay (static-test pipeline dry-run)
 * ---------------------------------------------------------------
 * The ESP32 plays a REAL motor thrust curve out its DAC (as if the motor were
 * pushing), samples it back on the ADC, and we integrate the result to recover
 * the total impulse. If the DAQ measures a KNOWN curve's impulse correctly, we
 * can trust it to measure a real motor.
 *
 * Curve: {path.split('/')[-1]}   Peak {f_max:.1f} N   True impulse {i_true:.2f} N*s
 * Generated by gen_thrust_firmware.py -- do not edit by hand.
 *
 * Wiring: GPIO25 (DAC) -> GPIO34 (ADC), one jumper.
 */
#include <Arduino.h>

static const int DAC_PIN = 25, ADC_PIN = 34;
static const int N = {n};
static const int STEP_US = {int(DT_MS*1000)};
static const uint8_t curve[N] = {{ {arr} }};

static uint16_t adcMv[N];
static volatile int i = 0;
static volatile bool tick = false;
static bool dumped = false;
hw_timer_t *timer = nullptr;

void IRAM_ATTR onTimer() {{ tick = true; }}

void setup() {{
  Serial.begin(115200);
  delay(300);
  analogReadResolution(12);
  analogSetAttenuation(ADC_11db);
  dacWrite(DAC_PIN, curve[0]);
  timer = timerBegin(0, 80, true);           // 1 tick = 1 us
  timerAttachInterrupt(timer, &onTimer, true);
  timerAlarmWrite(timer, STEP_US, true);
  timerAlarmEnable(timer);
}}

void loop() {{
  if (tick) {{
    tick = false;
    if (i < N) {{
      dacWrite(DAC_PIN, curve[i]);       // play this instant of the thrust curve
      delayMicroseconds(60);             // let the DAC settle
      adcMv[i] = analogReadMilliVolts(ADC_PIN);   // measure it back (calibrated)
      i++;
    }} else if (!dumped) {{
      dumped = true;
      Serial.println("# BLOCK THRUST_REPLAY DT_MS={DT_MS} N=" + String(N));
      Serial.println("i,dac_played,adc_mv");
      for (int k = 0; k < N; k++) {{
        Serial.print(k); Serial.print(",");
        Serial.print(curve[k]); Serial.print(",");
        Serial.println(adcMv[k]);
      }}
      Serial.println("# END");
      delay(3000);
      i = 0; dumped = false;             // replay again so the PC always catches it
    }}
  }}
}}
"""
    import os
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(firmware)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
