/*
 * DAQ Fase 4 -- Thrust-curve replay (static-test pipeline dry-run)
 * ---------------------------------------------------------------
 * The ESP32 plays a REAL motor thrust curve out its DAC (as if the motor were
 * pushing), samples it back on the ADC, and we integrate the result to recover
 * the total impulse. If the DAQ measures a KNOWN curve's impulse correctly, we
 * can trust it to measure a real motor.
 *
 * Curve: E.eng   Peak 178.7 N   True impulse 72.74 N*s
 * Generated by gen_thrust_firmware.py -- do not edit by hand.
 *
 * Wiring: GPIO25 (DAC) -> GPIO34 (ADC), one jumper.
 */
#include <Arduino.h>

static const int DAC_PIN = 25, ADC_PIN = 34;
static const int N = 218;
static const int STEP_US = 2000;
static const uint8_t curve[N] = { 30, 201, 201, 201, 202, 202, 202, 202, 203, 203, 203, 203, 203, 203, 204, 204, 204, 204, 204, 205, 205, 205, 205, 205, 206, 206, 206, 206, 206, 207, 207, 207, 207, 207, 207, 208, 208, 208, 208, 208, 209, 209, 209, 209, 209, 209, 210, 210, 210, 210, 210, 211, 211, 211, 211, 211, 211, 212, 212, 212, 212, 212, 212, 213, 213, 213, 213, 213, 213, 213, 214, 214, 214, 214, 214, 214, 215, 215, 215, 215, 215, 215, 216, 216, 216, 216, 216, 216, 216, 217, 217, 217, 217, 217, 217, 217, 218, 218, 218, 218, 218, 218, 218, 219, 219, 219, 219, 219, 219, 219, 220, 220, 220, 220, 220, 220, 220, 220, 221, 221, 221, 221, 221, 221, 221, 221, 222, 222, 222, 222, 222, 222, 222, 222, 223, 223, 223, 223, 223, 223, 223, 223, 223, 224, 224, 224, 224, 224, 224, 224, 224, 224, 225, 225, 225, 225, 225, 225, 225, 225, 225, 225, 226, 226, 226, 226, 226, 226, 226, 226, 226, 226, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 228, 228, 228, 228, 228, 228, 228, 228, 228, 228, 228, 228, 229, 229, 229, 229, 229, 229, 229, 229, 229, 229, 229, 229, 229, 230, 230, 230, 230, 230, 230, 230, 230, 30 };

static uint16_t adcMv[N];
static volatile int i = 0;
static volatile bool tick = false;
static bool dumped = false;
hw_timer_t *timer = nullptr;

void IRAM_ATTR onTimer() { tick = true; }

void setup() {
  Serial.begin(115200);
  delay(300);
  analogReadResolution(12);
  analogSetAttenuation(ADC_11db);
  dacWrite(DAC_PIN, curve[0]);
  timer = timerBegin(0, 80, true);           // 1 tick = 1 us
  timerAttachInterrupt(timer, &onTimer, true);
  timerAlarmWrite(timer, STEP_US, true);
  timerAlarmEnable(timer);
}

void loop() {
  if (tick) {
    tick = false;
    if (i < N) {
      dacWrite(DAC_PIN, curve[i]);       // play this instant of the thrust curve
      delayMicroseconds(60);             // let the DAC settle
      adcMv[i] = analogReadMilliVolts(ADC_PIN);   // measure it back (calibrated)
      i++;
    } else if (!dumped) {
      dumped = true;
      Serial.println("# BLOCK THRUST_REPLAY DT_MS=2.0 N=" + String(N));
      Serial.println("i,dac_played,adc_mv");
      for (int k = 0; k < N; k++) {
        Serial.print(k); Serial.print(",");
        Serial.print(curve[k]); Serial.print(",");
        Serial.println(adcMv[k]);
      }
      Serial.println("# END");
      delay(3000);
      i = 0; dumped = false;             // replay again so the PC always catches it
    }
  }
}
